author: wybosys@gmail.com
dependencies:
  flutter: {sdk: flutter}
  flutter_webview_plugin: ^0.3.7
  nnt: {path: ../nnt}
  shared_preferences: ^0.5.3
description: Nn Toolkit system implementation.
dev_dependencies:
  build_runner: ^1.6.6
  flutter_test: {sdk: flutter}
  source_gen: ^0.9.4
environment: {sdk: '>=2.1.0 <3.0.0'}
flutter:
  plugin: {androidPackage: com.nnt.impl.impl, pluginClass: ImplPlugin}
homepage: github.com/wybosys
name: impl
version: 0.0.1
