#!/usr/bin/env bash

npm run build

js_embeded=`cat dist/embeded.es5.min.js`

target='../../nnt/lib/gui/jsbridge.raw.dart'
echo 'part of nnt.gui;'> $target
echo "const JS_EMBEDED='''$js_embeded''';" >> $target