author: wybosys@gmail.com
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_webview_plugin: ^0.4.0
  nnt:
    path: ../nnt
description: Nn Toolkit system implementation.
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0    
  mustache: ^1.1.1
  source_gen: ^1.2.1
environment:
  sdk: '>=2.15.0 <3.0.0'
flutter:
  uses-material-design: true
  plugin:
    androidPackage: com.nnt.os
    pluginClass: OsPlugin
homepage: github.com/wybosys
name: os
version: 0.0.1
