builders:
  clazzes:
    import: "package:nnt/annotation/builder.dart"
    builder_factories: ["clazzes"]
    build_extensions: {".dart": ["clazz.g.part"]}
    auto_apply: all_packages
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  registers:
    import: "package:nnt/annotation/builder.dart"
    builder_factories: ["registers"]
    build_extensions: {".dart": ["register.g.part"]}
    auto_apply: all_packages
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      nnt:clazzes:
        generate_for:
          - lib/*.dart
      nnt:registers:
        generate_for:
          - lib/*.dart
