builders:
  clazz_generator:
    import: "package:nnt/annotation.dart"
    builder_factories: ["clazzBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: all_packages
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

targets:
  $default:
    builders:
      nnt:clazz_generator:
        generate_for:
          - lib/*.dart