builders:
  clazz_generator:
    import: "package:nnt/annotation.dart"
    builder_factories: ["clazzBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: root_package
    build_to: source

