targets:
  $default:
    builders:
      clazz_generator:
        enabled: true

builders:
  clazz_generator:
    import: "package:nnt/annotation.dart"
    builder_factories: ["clazzBuilder"]
    build_extensions: {".dart": [".g.part"]}
    auto_apply: all_packages
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
