author: wybosys@gmail.com
dependencies:
  ansicolor: ^1.0.2
  flutter: {sdk: flutter}
  http: ^0.12.0
  reflected_mustache: ^1.0.11
description: Nn Toolkit.
dev_dependencies:
  build_runner: ^1.6.6
  flutter_test: {sdk: flutter}
  mustache: ^1.1.1
  source_gen: ^0.9.4
environment: {sdk: '>=2.1.0 <3.0.0'}
flutter: null
homepage: github.com/wybosys
name: nnt
version: 0.0.1
