#!/usr/bin/env python3

import os

def FlushAnnotation():
    #os.system(flutter packages pub run build_runner clean)
    open('lib/annotation.g.dart', 'w').write("part of nnt.annotation;void _RegisterClazzes() {}")
    os.system('flutter packages pub run build_runner build --delete-conflicting-outputs')

if __name__ == "__main__":
    FlushAnnotation()
