#!/usr/bin/env bash

flutter packages pub run build_runner clean
echo "part of nnt.annotation;void _RegisterFactoryClasses() {}" > lib/annotation.g.dart
flutter packages pub run build_runner build --delete-conflicting-outputs
